language: c
compiler: 
 - gcc

before_install: 
 - sudo apt-get install -y build-essential p7zip-full diffstat texinfo chrpath libssl-dev libcurl4-openssl-dev libexpat-dev gettext

install: 
 - ./configure --without-tcl

script: make all

after_success: 
 - tar -vczf git-1.8.1.2_travis.tar.gz *
 - openssl aes-256-cbc -k "$KEY" -in .travis/travis-ci -d -a -out ./travis/travis-ci
 - chmod 600 .travis/travis-ci
 - ssh-add .travis/travis-ci
 - git clone git@github.com:CoderDojo/galileo-system-image.git
 - cp git-1.8.1.2_travis.tar.gz galileo-system-image.git
 - cd galileo-system-image
 - git commit -a -m 'Adding git 1.8.1.2'
 - git push

env: 
  global: 
    secure: yfvuRYFRz4X/esfxLanqgbg1XGUDaHaNQPV1X0fuFG5rMzDcFDZ4QQ9ZDpSZscqWZZhPMVAqB88x7lQmq9Br4EBcmdEezInESurFkEZNyRAhkd64gpCt5Njap/cnQpcJ5QNhjPrR14ne6ZdGh8LJKhcdmw6nLgIMVVcgZmNYMco=
