language: c
compiler: 
 - gcc

env: 
  global: 
  - secure: BeHQ65hN5TiUHrHT0wv/2izaf0GZkDGDicaYwSP2YbdtBVT8I3ejvkGSCoHLQwzjDXVzflKBQx8yNlQofJUXKY3Py2Y0iRNjIyHvUZtatxaxe0CrOEbeNCjyElAUjfd/lHVN4WER46sAWVfJQV9P0kcEw2UbgBIDMJ57qjYLDas=
  - secure: aLDX1pnEb4n3pphR5Wof/LvfsM4ZksNaqnHvPAv38GqDm47nOGizrfxodQpYq6tsVn9yAcDJtaj5kfi1+EfHvNGUe70LKuc+t1ThS2/WfKTHtc6hCgZChYtQ3u4438oPuwQ18vPbB1+9/eqz36OoEamXe75D/KIJEsVJxpn+KMw=
  - secure: CQK9KGcInMoZBRXtVkvYrdqZvXY8kdJ+fTE9Rv/iXzopfMkW3eNDS1QlavZZmZjUvPQy9nRdTicQJzVr9rmpMHNb35Cy35HBdJ4KhJoiKkaTlt/H64b0UOZAZhoie7R3fYd89VW3WXzHCsdW945jvXZjxzm+HXnLdHPSEMjOgz0=

before_install: 
 - sudo apt-get install -y build-essential p7zip-full diffstat texinfo chrpath libssl-dev libcurl4-openssl-dev libexpat-dev gettext

install: 
 - ./configure --without-tcl

script: make all

after_success: 
 - git remote set-url --push origin https://$GH_TOKEN@github.com/alan-donnelly/git-1.8.1.2.git
 - git config user.name $GIT_USER
 - git config user.email $GIT_EMAIL
 - git add -f *
 - git commit -a -m 'Adding git 1.8.1.2'
 - git tag -a 1.8.1.2 -m "Version 1.8.1.2"
 - git push origin 1.8.1.2

