#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /home/travis/build/alan-donnelly/galileo-git and test-date.

GIT_EXEC_PATH='/home/travis/build/alan-donnelly/galileo-git'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='/home/travis/build/alan-donnelly/galileo-git/templates/blt'
	export GIT_TEMPLATE_DIR
fi
GITPERLLIB='/home/travis/build/alan-donnelly/galileo-git/perl/blib/lib'
GIT_TEXTDOMAINDIR='/home/travis/build/alan-donnelly/galileo-git/po/build/locale'
PATH='/home/travis/build/alan-donnelly/galileo-git/bin-wrappers:'"$PATH"
export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

exec "${GIT_EXEC_PATH}/test-date" "$@"
